blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/Josverl/AAandCQManagementApp/discussions
    about: Please ask and search for answer questions here.



