name: CI / CD

on:
  push:
    paths:
      - solutions/**
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pack TeamsAACQOrchestrator
        uses: ./.github/actions/pack-solution
        with:
          name: TeamsAACQOrchestrator

      - uses: actions/upload-artifact@v2
        with:
          name: packed-solutions
          path: packed-solutions

  deploy-to-test:
    if: ${{ startsWith(github.ref_name , 'Dev' ) || startsWith(github.ref_name , 'alm' ) || github.ref_name == 'main'}}  # if the branch is 'Dev', was main
    strategy:
      matrix:
        environment: [test-jos1]
    environment: ${{ matrix.environment }}
    
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: packed-solutions

      - name: Import TACO (TeamsAACQOrchestrator)
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          solution-file: TeamsAACQOrchestrator_managed.zip
          environment-url:  "${{ secrets.CSD_ENVIRONMENT_URL }}"
          tenant-id: "${{ secrets.APP_TENANT_ID }}"
          app-id: "${{ secrets.APP_ID }}"
          client-secret: "${{ secrets.APP_SECRET }}"
